### PR TITLE
Allow purchases from `ExampleNFT` contract

### PR DESCRIPTION
**Pull request by m-Peter**
Closes: #???

## Description

- Update import paths for Cadence files after the recent directory restructure,
- Update contract declaration for `FungibleToken` in `flow.json` config file,
- Allow any account to purchase `ExampleNFT` NFTs

## Context

The [ExampleNFT](https://flow-view-source.com/testnet/account/0xa60cf32e8369f919/contract/ExampleNFT) smart contract is already deployed on Testnet, and it is also part of the [NFTCatalog](https://nft-catalog.vercel.app/catalog/testnet/example). However, it is impossible for other Testnet accounts to obtain such NFTs, without a transaction from the account that owns a `ExampleNFT.NFTMinter` resource. This is rather cumbersome, when developers do not have any other means to own an NFT from a smart contract that is present in the `NFTCatalog`. Hence, we added a smart contract function and a corresponding transaction to facilitate this need, by allowing any account to purchase an `ExampleNFT` NFT.
______

For contributor use:

- [x] Targeted PR against `master` branch
- [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Code follows the [standards mentioned here](https://github.com/onflow/flow-nft/blob/master/CONTRIBUTING.md#styleguides).
- [ ] Updated relevant documentation 
- [x] Re-reviewed `Files changed` in the Github PR explorer
- [ ] Added appropriate labels 

- [ ] Update the version in package.json when there is a change in the smart contracts

### CODE REVIEW

**Comment by m-Peter** [comment]
```bash
flow emulator --storage-limit=false -v

flow project deploy --network=emulator

flow keys generate --output=json > peter.json 

cat peter.json

# supply the key from the above file
flow accounts create --key

flow transactions send ./transactions/transfer_flow_tokens.cdc 0x01cf0e2f2f715450 1500.0 --network=emulator --signer=emulator-account

flow scripts execute ./scripts/get_total_supply.cdc --network=emulator

flow transactions send ./transactions/setup_account.cdc --network=emulator --signer=peter

flow scripts execute ./scripts/get_collection_ids.cdc 0x01cf0e2f2f715450 --network=emulator

flow scripts execute ./scripts/get_collection_length.cdc 0x01cf0e2f2f715450 --network=emulator

flow transactions send ./transactions/setup_account_to_receive_royalty.cdc '/storage/flowTokenVault' --network=emulator --signer=emulator-account

flow transactions send ./transactions/mint_nft.cdc 0x01cf0e2f2f715450 'My Example NFT' 'My Example NFT Description' 'https://www.example-nft.com/thumbnails/0' '[0.05]' '["Tribute to Creator!"]' '[0xf8d6e0586b0a20c7]' --network=emulator --signer=emulator-account

flow transactions send ./transactions/purchase_nft.cdc 'My Example NFT #2' 'My Example NFT Description #2' 'https://www.example-nft.com/thumbnails/1' '[0.02]' '["Tribute to Creator!"]' '[0xf8d6e0586b0a20c7]' --network=emulator --signer=peter

flow scripts execute ./scripts/get_nft_metadata.cdc 0x01cf0e2f2f715450 0 --network=emulator

flow scripts execute ./scripts/get_nft_view.cdc 0x01cf0e2f2f715450 1 --network=emulator

flow scripts execute ./scripts/borrow_nft.cdc 0x01cf0e2f2f715450 0 --network=emulator

```

The above sequence of commands, was used to test the functionality locally, with a running emulator.

**Review by joshuahannan — COMMENTED** [review]
I think this is probably the wrong place to make these changes. If you want something to be easier to use with NFT Catalog, I would recommend chatting with the owners of it to see if you can get support for this added. I wasn't even aware that there was an ExampleNFT contract deployed on testnet that people were using, so that is out of our control, and out of view of this repo. This example NFT contract is meant to be as simple as possible and not be geared to work with any specific product.

Does that make sense?

**Comment by m-Peter** [comment]
Hi @joshuahannan, thanks for the reply & feedback. My bad, I thought that this `ExampleNFT` contract was actually implemented in this repository :sweat_smile:. After searching around, I think the best place for this functionality is the https://github.com/dapperlabs/nft-catalog repository.

> This example NFT contract is meant to be as simple as possible and not be geared to work with any specific product.

I understand that, our intention was not to build a live product around it. It was just to enhance developer experience, when building products/solutions that integrate with the `NFTCatalog`. The purchase functionality is merely to allow developers with Testnet accounts, to acquire such NFTs, simply for development purposes. I added a purchase feature, merely to avoid abuse, and require developers to make a symbolic payment with Flow tokens. I hope that makes sense now :pray:

**Comment by joshuahannan** [comment]
Yeah, I think this is a good idea! Just not the right place for it here. but thanks for proposing it. I hope the NFT catalog team finds it useful too. :)

**Pull request closed without merging**
