### PR TITLE
remove file path syntax for imports

### PR DESCRIPTION
**Pull request by austinkline**
Closes: #???

## Description

Removes the file path imports since new versions of the flow cli don't need it. If we do this, you can use submodules to pull in standard repos so you don't have to copy other contracts anymore!

______

For contributor use:

- [ ] Targeted PR against `master` branch
- [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Code follows the [standards mentioned here](https://github.com/onflow/flow-nft/blob/master/CONTRIBUTING.md#styleguides).
- [ ] Updated relevant documentation 
- [ ] Re-reviewed `Files changed` in the Github PR explorer
- [ ] Added appropriate labels 

- [ ] Update the version in package.json when there is a change in the smart contracts

### CODE REVIEW

**Comment by bluesign** [comment]
shouldn't be something like: `import "NonFungibleToken"` instead of `import NonFungibleToken from "NonFungibleToken"`

**Comment by austinkline** [comment]
> shouldn't be something like: `import "NonFungibleToken"` instead of `import NonFungibleToken from "NonFungibleToken"`

You're right! Tried that just now and it works as well. I could have sworn when I tried it a week back, my imports didn't resolve. I will amend this to use:

```cadence
import "MetadataViews"
```

instead of 

```cadence
import MetadataViews from "MetadataViews"
```

**Comment by austinkline** [comment]
Looks like changing syntax made js tests break. Does flow-js-testing support that yet?

**Comment by joshuahannan** [comment]
Yeah, we weren't ready to update to the new syntax because it wasn't compatible with our existing tests and repo organization yet, but this might work now. @sisyphusSmiling or @satyamakgec can you take a look at the js tests and see what might be going wrong?

**Comment by austinkline** [comment]
> Yeah, we weren't ready to update to the new syntax because it wasn't compatible with our existing tests and repo organization yet, but this might work now.

I can always revert the last commit of this PR and we can tackle the final bit of it once support is there, I'm not blocked on this so whatever folks on your end would rather

**Pull request closed without merging**
